import mongoose from 'mongoose';
import dotenv from 'dotenv';
import connectDB from '../config/dbConnection.js';
import MealTemplate from '../models/MealTemplate.js';

dotenv.config();

const SEED_DATA_NOTICE =
  'Calories and macronutrients are approximate seed data for a university prototype. Generated meal plans require doctor review and approval before being shown to patients.';

const meals = [
  // =========================================================================
  // BREAKFAST MEALS (14 Meals)
  // =========================================================================
  {
    name: 'Red Rice Milk Rice with Lunu Miris',
    mealType: 'Breakfast',
    description: 'Traditional Sri Lankan milk rice made with red rice and served with a spicy onion sambol.',
    portionSize: '2 medium squares (150g)',
    calories: 350,
    protein: 6,
    carbohydrates: 55,
    fat: 10,
    fiber: 4,
    ingredients: ['Red Rice', 'Coconut Milk', 'Onion', 'Chili Flakes', 'Lime', 'Salt'],
    dietaryTypes: ['Vegan', 'Vegetarian', 'No Special Preference'],
    allergens: [],
    suitableFor: ['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'String Hoppers with Dhal and Pol Sambol',
    mealType: 'Breakfast',
    description: 'Steamed rice flour noodles served with lentil curry and coconut sambol.',
    portionSize: '10 string hoppers with 1/2 cup dhal',
    calories: 300,
    protein: 8,
    carbohydrates: 50,
    fat: 6,
    fiber: 5,
    ingredients: ['Rice Flour', 'Lentils', 'Coconut', 'Spices'],
    dietaryTypes: ['Vegan', 'Vegetarian', 'No Special Preference'],
    allergens: [],
    suitableFor: ['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II', 'Obesity_Type_I'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Pol Roti with Chicken Curry',
    mealType: 'Breakfast',
    description: 'Coconut flatbread served with a flavorful Sri Lankan chicken curry.',
    portionSize: '2 small rotis with 1/2 cup chicken curry',
    calories: 400,
    protein: 18,
    carbohydrates: 40,
    fat: 15,
    fiber: 4,
    ingredients: ['Wheat Flour', 'Coconut', 'Chicken', 'Curry Powder', 'Onion'],
    dietaryTypes: ['No Special Preference'],
    allergens: ['Gluten'],
    suitableFor: ['Insufficient_Weight', 'Normal_Weight', 'Overweight_Level_I'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Kurakkan Pittu with Katta Sambol and Warm Milk',
    mealType: 'Breakfast',
    description: 'Finger millet steamed cake served with spicy sambol and a glass of milk.',
    portionSize: '1 medium piece of pittu, 1 tbsp sambol, 1 cup milk',
    calories: 380,
    protein: 12,
    carbohydrates: 55,
    fat: 8,
    fiber: 6,
    ingredients: ['Kurakkan Flour', 'Wheat Flour', 'Coconut', 'Onion', 'Chili', 'Cow Milk'],
    dietaryTypes: ['Vegetarian', 'No Special Preference'],
    allergens: ['Gluten', 'Milk & Dairy'],
    suitableFor: ['Normal_Weight', 'Overweight_Level_I'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Boiled Green Gram with Grated Coconut',
    mealType: 'Breakfast',
    description: 'Nutritious boiled mung beans garnished with fresh grated coconut.',
    portionSize: '1 cup green gram',
    calories: 250,
    protein: 14,
    carbohydrates: 45,
    fat: 4,
    fiber: 10,
    ingredients: ['Green Gram', 'Coconut', 'Salt'],
    dietaryTypes: ['Vegan', 'Vegetarian', 'No Special Preference'],
    allergens: [],
    suitableFor: ['Overweight_Level_II', 'Obesity_Type_I', 'Obesity_Type_II', 'Obesity_Type_III'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Tempered Chickpeas with Curry Leaves',
    mealType: 'Breakfast',
    description: 'Boiled chickpeas stir-fried with mustard seeds, onions, and curry leaves.',
    portionSize: '1 cup tempered chickpeas',
    calories: 280,
    protein: 10,
    carbohydrates: 40,
    fat: 7,
    fiber: 9,
    ingredients: ['Chickpeas', 'Onion', 'Curry Leaves', 'Mustard Seeds', 'Coconut Oil'],
    dietaryTypes: ['Vegan', 'Vegetarian', 'No Special Preference'],
    allergens: [],
    suitableFor: ['Overweight_Level_I', 'Overweight_Level_II', 'Obesity_Type_I', 'Obesity_Type_II'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Oats Porridge with Fresh Fruits',
    mealType: 'Breakfast',
    description: 'Rolled oats cooked in low-fat milk, topped with local fresh fruits.',
    portionSize: '1 bowl',
    calories: 220,
    protein: 10,
    carbohydrates: 35,
    fat: 4,
    fiber: 6,
    ingredients: ['Oats', 'Low-fat Milk', 'Banana', 'Papaya', 'Cinnamon'],
    dietaryTypes: ['Vegetarian', 'No Special Preference'],
    allergens: ['Gluten', 'Milk & Dairy'],
    suitableFor: ['Obesity_Type_I', 'Obesity_Type_II', 'Obesity_Type_III'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Egg Hoppers with Seeni Sambol',
    mealType: 'Breakfast',
    description: 'Bowl-shaped rice flour pancakes with a baked egg and sweet onion relish.',
    portionSize: '1 egg hopper, 1 plain hopper, 2 tbsp seeni sambol',
    calories: 320,
    protein: 10,
    carbohydrates: 45,
    fat: 8,
    fiber: 3,
    ingredients: ['Rice Flour', 'Coconut Milk', 'Egg', 'Onion', 'Sugar'],
    dietaryTypes: ['No Special Preference'],
    allergens: ['Egg'],
    suitableFor: ['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Whole Wheat Bread with Scrambled Eggs',
    mealType: 'Breakfast',
    description: 'Toasted whole wheat bread served with Sri Lankan style scrambled eggs.',
    portionSize: '2 slices bread, 2 eggs',
    calories: 310,
    protein: 16,
    carbohydrates: 30,
    fat: 12,
    fiber: 5,
    ingredients: ['Whole Wheat Bread', 'Egg', 'Tomato', 'Onion', 'Green Chili'],
    dietaryTypes: ['No Special Preference'],
    allergens: ['Gluten', 'Egg', 'Acidic Fruits'],
    suitableFor: ['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Sago Porridge with Cashews',
    mealType: 'Breakfast',
    description: 'Warm sago pearls cooked in thin coconut milk with roasted cashews.',
    portionSize: '1 bowl',
    calories: 260,
    protein: 3,
    carbohydrates: 45,
    fat: 6,
    fiber: 1,
    ingredients: ['Sago', 'Coconut Milk', 'Cashew Nuts', 'Jaggery'],
    dietaryTypes: ['Vegan', 'Vegetarian', 'No Special Preference'],
    allergens: ['Peanuts, Tree Nuts & Soy'],
    suitableFor: ['Insufficient_Weight', 'Normal_Weight'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Steamed Manioc with Kochchi Sambol and Boiled Egg',
    mealType: 'Breakfast',
    description: 'Traditional boiled cassava root served with hot bird eye chili sambol and a protein-rich egg.',
    portionSize: '1 cup boiled manioc, 1 boiled egg, 1 tbsp sambol',
    calories: 340,
    protein: 9,
    carbohydrates: 58,
    fat: 8,
    fiber: 5,
    ingredients: ['Manioc', 'Egg', 'Kochchi Chili', 'Coconut', 'Lime', 'Salt'],
    dietaryTypes: ['No Special Preference'],
    allergens: ['Egg'],
    suitableFor: ['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Kurakkan Thuppa Porridge with Fresh Milk',
    mealType: 'Breakfast',
    description: 'Finger millet porridge simmered with cow milk, cardamom, and a hint of kitul treacle.',
    portionSize: '1 bowl (250ml)',
    calories: 230,
    protein: 7,
    carbohydrates: 40,
    fat: 4,
    fiber: 6,
    ingredients: ['Kurakkan Flour', 'Cow Milk', 'Cardamom', 'Kithul Treacle'],
    dietaryTypes: ['Vegetarian', 'No Special Preference'],
    allergens: ['Milk & Dairy'],
    suitableFor: ['Overweight_Level_I', 'Overweight_Level_II', 'Obesity_Type_I', 'Obesity_Type_II', 'Obesity_Type_III'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Prawn and Leek Omelette with Whole Wheat Toast',
    mealType: 'Breakfast',
    description: 'Fluffy egg omelette pan-fried with small sea prawns and leeks, served with whole wheat toast.',
    portionSize: '2-egg omelette with 50g prawns, 1 slice toast',
    calories: 330,
    protein: 24,
    carbohydrates: 20,
    fat: 16,
    fiber: 3,
    ingredients: ['Egg', 'Prawns', 'Leeks', 'Whole Wheat Bread', 'Black Pepper', 'Coconut Oil'],
    dietaryTypes: ['No Special Preference'],
    allergens: ['Egg', 'Seafood / Shellfish', 'Gluten'],
    suitableFor: ['Insufficient_Weight', 'Normal_Weight', 'Overweight_Level_I'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Boiled Kadala with Maldive Fish and Coconut',
    mealType: 'Breakfast',
    description: 'Boiled white chickpeas tempered with curry leaves, mustard seeds, fresh coconut, and crushed Maldive fish.',
    portionSize: '1 cup tempered kadala',
    calories: 295,
    protein: 13,
    carbohydrates: 42,
    fat: 8,
    fiber: 9,
    ingredients: ['Chickpeas', 'Maldive Fish', 'Coconut', 'Onion', 'Curry Leaves', 'Mustard Seeds'],
    dietaryTypes: ['No Special Preference'],
    allergens: ['Strong Fish Types & Maldive Fish'],
    suitableFor: ['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II'],
    medicalWarnings: [],
    isActive: true
  },

  // =========================================================================
  // LUNCH MEALS (13 Meals)
  // =========================================================================
  {
    name: 'Red Rice with Chicken Curry and Gotukola Sambol',
    mealType: 'Lunch',
    description: 'Nutritious red rice served with protein-rich chicken curry, dhal, and fresh leafy greens.',
    portionSize: '1 cup rice, 1/2 cup chicken, 1/4 cup sambol',
    calories: 450,
    protein: 25,
    carbohydrates: 55,
    fat: 12,
    fiber: 6,
    ingredients: ['Red Rice', 'Chicken', 'Lentils', 'Gotukola', 'Coconut'],
    dietaryTypes: ['No Special Preference'],
    allergens: [],
    suitableFor: ['Insufficient_Weight', 'Normal_Weight'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'White Rice with Fried Fish and Beans Curry',
    mealType: 'Lunch',
    description: 'Classic local lunch of white rice, lightly fried sea fish, and green beans.',
    portionSize: '1 cup rice, 1 piece fish, 1/2 cup beans',
    calories: 420,
    protein: 22,
    carbohydrates: 50,
    fat: 14,
    fiber: 5,
    ingredients: ['White Rice', 'Fish', 'Green Beans', 'Spices'],
    dietaryTypes: ['No Special Preference'],
    allergens: ['Strong Fish Types & Maldive Fish'],
    suitableFor: ['Insufficient_Weight', 'Normal_Weight'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Brown Rice with Soya Meat Curry and Salad',
    mealType: 'Lunch',
    description: 'High-fiber brown rice paired with spicy soya chunks and fresh cabbage salad.',
    portionSize: '1 cup rice, 1/2 cup soya, 1/2 cup salad',
    calories: 380,
    protein: 18,
    carbohydrates: 60,
    fat: 5,
    fiber: 8,
    ingredients: ['Brown Rice', 'Soya Chunks', 'Cabbage', 'Carrot', 'Lime'],
    dietaryTypes: ['Vegan', 'Vegetarian', 'No Special Preference'],
    allergens: ['Peanuts, Tree Nuts & Soy'],
    suitableFor: [
      'Normal_Weight',
      'Overweight_Level_I',
      'Overweight_Level_II',
      'Obesity_Type_I',
      'Obesity_Type_II',
      'Obesity_Type_III'
    ],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Yellow Rice with Beef Curry and Brinjal Moju',
    mealType: 'Lunch',
    description: 'Festive yellow rice served with rich beef curry and sweet-sour eggplant pickle.',
    portionSize: '1.5 cups rice, 1/2 cup beef, 2 tbsp moju',
    calories: 550,
    protein: 28,
    carbohydrates: 65,
    fat: 18,
    fiber: 5,
    ingredients: ['White Rice', 'Beef', 'Eggplant', 'Turmeric', 'Coconut Milk'],
    dietaryTypes: ['No Special Preference'],
    allergens: ['Red Meats', 'Certain Vegetables'],
    suitableFor: ['Insufficient_Weight'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Red Rice with Jackfruit Curry and Spinach',
    mealType: 'Lunch',
    description: 'Traditional village-style lunch with tender jackfruit curry, dhal, and spinach.',
    portionSize: '1 cup rice, 1/2 cup polos, 1/2 cup spinach',
    calories: 400,
    protein: 10,
    carbohydrates: 70,
    fat: 6,
    fiber: 12,
    ingredients: ['Red Rice', 'Jackfruit', 'Spinach', 'Lentils', 'Coconut Milk'],
    dietaryTypes: ['Vegan', 'Vegetarian', 'No Special Preference'],
    allergens: [],
    suitableFor: ['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Mixed Vegetable Fried Rice with Fried Egg',
    mealType: 'Lunch',
    description: 'Lightly stir-fried rice with mixed local vegetables, topped with a fried egg.',
    portionSize: '1.5 cups rice, 1 egg',
    calories: 420,
    protein: 14,
    carbohydrates: 55,
    fat: 15,
    fiber: 4,
    ingredients: ['White Rice', 'Carrot', 'Leeks', 'Egg', 'Soy Sauce'],
    dietaryTypes: ['No Special Preference'],
    allergens: ['Egg', 'Peanuts, Tree Nuts & Soy', 'Gluten'],
    suitableFor: ['Normal_Weight', 'Overweight_Level_I'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'String Hopper Biryani with Chicken',
    mealType: 'Lunch',
    description: 'A twist on biryani using string hoppers, cooked with chicken pieces and spices.',
    portionSize: '1.5 cups mixed biryani',
    calories: 460,
    protein: 22,
    carbohydrates: 50,
    fat: 16,
    fiber: 4,
    ingredients: ['Rice Flour', 'Chicken', 'Biryani Spices', 'Onion', 'Ghee'],
    dietaryTypes: ['No Special Preference'],
    allergens: ['Milk & Dairy'],
    suitableFor: ['Insufficient_Weight', 'Normal_Weight'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Brown Rice with Grilled Fish and Tomato Salad',
    mealType: 'Lunch',
    description: 'Healthy lunch option featuring grilled fish fillet and fresh tomato salad.',
    portionSize: '1 cup rice, 1 piece fish, 1 cup salad',
    calories: 390,
    protein: 26,
    carbohydrates: 45,
    fat: 8,
    fiber: 6,
    ingredients: ['Brown Rice', 'Fish', 'Tomato', 'Cucumber', 'Lime'],
    dietaryTypes: ['No Special Preference'],
    allergens: ['Strong Fish Types & Maldive Fish', 'Acidic Fruits'],
    suitableFor: [
      'Normal_Weight',
      'Overweight_Level_I',
      'Overweight_Level_II',
      'Obesity_Type_I',
      'Obesity_Type_II',
      'Obesity_Type_III'
    ],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Rice and Curry with Canned Fish',
    mealType: 'Lunch',
    description: 'Everyday meal of rice, canned fish curry, ash plantain, and leafy greens.',
    portionSize: '1 cup rice, 1/2 cup fish curry, 1/2 cup veggies',
    calories: 430,
    protein: 20,
    carbohydrates: 60,
    fat: 10,
    fiber: 5,
    ingredients: ['White Rice', 'Canned Fish', 'Ash Plantain', 'Gotukola'],
    dietaryTypes: ['No Special Preference'],
    allergens: ['Strong Fish Types & Maldive Fish'],
    suitableFor: ['Normal_Weight', 'Overweight_Level_I'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Red Rice with Spicy Prawn Curry and Mukunuwenna',
    mealType: 'Lunch',
    description: 'Traditional red rice with Ceylon spiced prawn curry, yellow lentils, and shredded mukunuwenna greens.',
    portionSize: '1 cup red rice, 1/2 cup prawn curry, 1/2 cup greens',
    calories: 430,
    protein: 24,
    carbohydrates: 58,
    fat: 10,
    fiber: 7,
    ingredients: ['Red Rice', 'Prawns', 'Mukunuwenna', 'Lentils', 'Coconut Milk', 'Spices'],
    dietaryTypes: ['No Special Preference'],
    allergens: ['Seafood / Shellfish'],
    suitableFor: ['Insufficient_Weight', 'Normal_Weight', 'Overweight_Level_I'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'White Rice with Black Pork Curry and Breadfruit',
    mealType: 'Lunch',
    description: 'Southern style black pork curry served with tender breadfruit curry and steamed white rice.',
    portionSize: '1 cup rice, 80g pork curry, 1/2 cup breadfruit',
    calories: 520,
    protein: 26,
    carbohydrates: 62,
    fat: 18,
    fiber: 6,
    ingredients: ['White Rice', 'Pork', 'Breadfruit', 'Black Pepper', 'Goraka', 'Coconut Milk'],
    dietaryTypes: ['No Special Preference'],
    allergens: ['Red Meats', 'Certain Vegetables'],
    suitableFor: ['Insufficient_Weight', 'Normal_Weight'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Red Rice with Cuttlefish Roast and Gotukola Sambol',
    mealType: 'Lunch',
    description: 'Spiced tempered cuttlefish with capsicums, served with country red rice and gotukola salad.',
    portionSize: '1 cup red rice, 1/2 cup cuttlefish, 1/4 cup sambol',
    calories: 410,
    protein: 26,
    carbohydrates: 54,
    fat: 9,
    fiber: 6,
    ingredients: ['Red Rice', 'Cuttlefish', 'Onion', 'Capsicum', 'Gotukola', 'Coconut'],
    dietaryTypes: ['No Special Preference'],
    allergens: ['Seafood / Shellfish'],
    suitableFor: ['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Brown Rice with Pineapple Curry and Kankun Mellum',
    mealType: 'Lunch',
    description: 'Tangy Ceylon pineapple curry served with yellow lentils, stir-fried kankun spinach, and brown rice.',
    portionSize: '1 cup brown rice, 1/2 cup pineapple curry, 1/2 cup dhal',
    calories: 370,
    protein: 11,
    carbohydrates: 68,
    fat: 5,
    fiber: 9,
    ingredients: ['Brown Rice', 'Pineapple', 'Lentils', 'Kankun', 'Coconut Milk', 'Spices'],
    dietaryTypes: ['Vegan', 'Vegetarian', 'No Special Preference'],
    allergens: ['Acidic Fruits'],
    suitableFor: ['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II', 'Obesity_Type_I', 'Obesity_Type_II'],
    medicalWarnings: [],
    isActive: true
  },

  // =========================================================================
  // DINNER MEALS (12 Meals)
  // =========================================================================
  {
    name: 'Kurakkan Roti with Dhal and Lunu Miris',
    mealType: 'Dinner',
    description: 'High-fiber flatbread made with finger millet, paired with lentil curry.',
    portionSize: '2 small rotis, 1/2 cup dhal',
    calories: 320,
    protein: 10,
    carbohydrates: 50,
    fat: 6,
    fiber: 8,
    ingredients: ['Kurakkan Flour', 'Wheat Flour', 'Lentils', 'Onion', 'Chili'],
    dietaryTypes: ['Vegan', 'Vegetarian', 'No Special Preference'],
    allergens: ['Gluten'],
    suitableFor: ['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II', 'Obesity_Type_I'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'String Hoppers with Fish Ambul Thiyal',
    mealType: 'Dinner',
    description: 'Light dinner of string hoppers with sour dry fish curry and coconut sambol.',
    portionSize: '10 string hoppers, 3 pieces fish',
    calories: 340,
    protein: 18,
    carbohydrates: 45,
    fat: 6,
    fiber: 4,
    ingredients: ['Rice Flour', 'Fish', 'Goraka', 'Black Pepper', 'Coconut'],
    dietaryTypes: ['No Special Preference'],
    allergens: ['Strong Fish Types & Maldive Fish'],
    suitableFor: ['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Red Rice with Soya Meat Curry',
    mealType: 'Dinner',
    description: 'Light vegetarian dinner with red rice, soya meat, and cucumber salad.',
    portionSize: '3/4 cup rice, 1/2 cup soya, 1/2 cup cucumber',
    calories: 300,
    protein: 15,
    carbohydrates: 45,
    fat: 4,
    fiber: 7,
    ingredients: ['Red Rice', 'Soya Chunks', 'Cucumber', 'Curry Powder'],
    dietaryTypes: ['Vegan', 'Vegetarian', 'No Special Preference'],
    allergens: ['Peanuts, Tree Nuts & Soy'],
    suitableFor: ['Overweight_Level_I', 'Overweight_Level_II', 'Obesity_Type_I', 'Obesity_Type_II'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Roast Paan with Lentil Soup and Chicken Curry',
    mealType: 'Dinner',
    description: 'Crispy local flat bread with creamy dhal and mild chicken curry.',
    portionSize: '2 slices bread, 1/2 cup dhal, 1/2 cup chicken',
    calories: 380,
    protein: 20,
    carbohydrates: 40,
    fat: 12,
    fiber: 5,
    ingredients: ['Wheat Flour', 'Lentils', 'Chicken', 'Coconut Milk'],
    dietaryTypes: ['No Special Preference'],
    allergens: ['Gluten'],
    suitableFor: [
      'Insufficient_Weight',
      'Normal_Weight',
      'Overweight_Level_I'
    ],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Plain Hoppers with Fish Curry',
    mealType: 'Dinner',
    description: 'Crispy rice flour bowl pancakes served with spicy fish curry.',
    portionSize: '3 plain hoppers, 1 piece fish with gravy',
    calories: 350,
    protein: 15,
    carbohydrates: 50,
    fat: 8,
    fiber: 3,
    ingredients: ['Rice Flour', 'Coconut Milk', 'Fish', 'Curry Spices'],
    dietaryTypes: ['No Special Preference'],
    allergens: ['Strong Fish Types & Maldive Fish'],
    suitableFor: ['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Boiled Vegetables with Grilled Chicken Breast',
    mealType: 'Dinner',
    description: 'A low-carb dinner featuring local veggies like carrots and beans with chicken breast.',
    portionSize: '1.5 cups vegetables, 100g chicken',
    calories: 280,
    protein: 30,
    carbohydrates: 20,
    fat: 6,
    fiber: 6,
    ingredients: ['Chicken Breast', 'Carrot', 'Green Beans', 'Black Pepper'],
    dietaryTypes: ['No Special Preference'],
    allergens: [],
    suitableFor: ['Overweight_Level_I', 'Overweight_Level_II', 'Obesity_Type_I', 'Obesity_Type_II', 'Obesity_Type_III'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Pittu with Egg Curry and Lunu Miris',
    mealType: 'Dinner',
    description: 'Steamed rice flour and coconut cylinders served with boiled egg curry.',
    portionSize: '1 medium piece pittu, 1 egg',
    calories: 360,
    protein: 12,
    carbohydrates: 45,
    fat: 12,
    fiber: 4,
    ingredients: ['Rice Flour', 'Wheat Flour', 'Coconut', 'Egg', 'Coconut Milk', 'Chili'],
    dietaryTypes: ['No Special Preference'],
    allergens: ['Gluten', 'Egg'],
    suitableFor: [
      'Insufficient_Weight',
      'Normal_Weight',
      'Overweight_Level_I',
      'Overweight_Level_II'
    ],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Vegetable Soup with Garlic Bread',
    mealType: 'Dinner',
    description: 'A warm, comforting vegetable broth served with a slice of garlic bread.',
    portionSize: '1 large bowl soup, 1 slice bread',
    calories: 250,
    protein: 6,
    carbohydrates: 35,
    fat: 8,
    fiber: 5,
    ingredients: ['Mixed Vegetables', 'Garlic', 'Wheat Flour', 'Butter'],
    dietaryTypes: ['Vegetarian', 'No Special Preference'],
    allergens: ['Gluten', 'Milk & Dairy'],
    suitableFor: ['Overweight_Level_II', 'Obesity_Type_I', 'Obesity_Type_II', 'Obesity_Type_III'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Kurakkan String Hoppers with Kiri Hodi and Pol Sambol',
    mealType: 'Dinner',
    description: 'Finger millet string hoppers served with turmeric coconut gravy and chili sambol.',
    portionSize: '10 kurakkan string hoppers, 1/2 cup gravy, 2 tbsp sambol',
    calories: 310,
    protein: 7,
    carbohydrates: 52,
    fat: 8,
    fiber: 7,
    ingredients: ['Kurakkan Flour', 'Rice Flour', 'Coconut Milk', 'Turmeric', 'Lime', 'Chili Flakes'],
    dietaryTypes: ['Vegan', 'Vegetarian', 'No Special Preference'],
    allergens: [],
    suitableFor: ['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II', 'Obesity_Type_I', 'Obesity_Type_II'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Devilled Chicken with Vegetable Stir Fry and Basmati Rice',
    mealType: 'Dinner',
    description: 'Spicy devilled chicken with fresh tomato and capsicum, served with steamed basmati and veggies.',
    portionSize: '100g chicken, 1/2 cup rice, 1 cup vegetables',
    calories: 370,
    protein: 28,
    carbohydrates: 42,
    fat: 9,
    fiber: 5,
    ingredients: ['Chicken Breast', 'Tomato', 'Capsicum', 'Basmati Rice', 'Carrot', 'Soy Sauce'],
    dietaryTypes: ['No Special Preference'],
    allergens: ['Acidic Fruits', 'Peanuts, Tree Nuts & Soy', 'Gluten'],
    suitableFor: ['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Egg Roti with Spicy Dhal Curry',
    mealType: 'Dinner',
    description: 'Whole wheat flatbread stuffed with egg and onions, served with savory yellow lentil curry.',
    portionSize: '1 medium egg roti, 1/2 cup dhal',
    calories: 360,
    protein: 15,
    carbohydrates: 44,
    fat: 13,
    fiber: 6,
    ingredients: ['Wheat Flour', 'Egg', 'Onion', 'Lentils', 'Green Chili', 'Coconut Oil'],
    dietaryTypes: ['No Special Preference'],
    allergens: ['Gluten', 'Egg'],
    suitableFor: ['Insufficient_Weight', 'Normal_Weight', 'Overweight_Level_I'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Jaffna Crab Curry with Bread and Pol Sambol',
    mealType: 'Dinner',
    description: 'Authentic spicy lagoon crab curry cooked with drumstick leaves, paired with bread and sambol.',
    portionSize: '1 medium crab in curry, 2 slices bread',
    calories: 410,
    protein: 32,
    carbohydrates: 40,
    fat: 12,
    fiber: 4,
    ingredients: ['Crab', 'Wheat Flour', 'Drumstick Leaves', 'Coconut Milk', 'Jaffna Curry Powder'],
    dietaryTypes: ['No Special Preference'],
    allergens: ['Seafood / Shellfish', 'Gluten'],
    suitableFor: ['Insufficient_Weight', 'Normal_Weight', 'Overweight_Level_I'],
    medicalWarnings: [],
    isActive: true
  },

  // =========================================================================
  // SNACKS (11 Meals)
  // =========================================================================
  {
    name: 'Fresh Papaya and Banana Bowl',
    mealType: 'Snack',
    description: 'A refreshing bowl of freshly cut local papaya and banana.',
    portionSize: '1 small bowl',
    calories: 120,
    protein: 1,
    carbohydrates: 30,
    fat: 0,
    fiber: 4,
    ingredients: ['Papaya', 'Banana'],
    dietaryTypes: ['Vegan', 'Vegetarian', 'No Special Preference'],
    allergens: [],
    suitableFor: ['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II', 'Obesity_Type_I', 'Obesity_Type_II', 'Obesity_Type_III'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Low-Fat Yoghurt with Kithul Treacle',
    mealType: 'Snack',
    description: 'A healthy alternative to curd, using low-fat yoghurt with a touch of kithul treacle.',
    portionSize: '1 small cup (80g)',
    calories: 150,
    protein: 6,
    carbohydrates: 25,
    fat: 2,
    fiber: 0,
    ingredients: ['Low-fat Milk Yoghurt', 'Kithul Treacle'],
    dietaryTypes: ['Vegetarian', 'No Special Preference'],
    allergens: ['Milk & Dairy'],
    suitableFor: ['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II', 'Obesity_Type_I', 'Obesity_Type_II'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Roasted Peanuts',
    mealType: 'Snack',
    description: 'Dry roasted peanuts tossed with a pinch of salt and chili powder.',
    portionSize: '1 small handful (30g)',
    calories: 200,
    protein: 8,
    carbohydrates: 6,
    fat: 16,
    fiber: 3,
    ingredients: ['Peanuts', 'Salt', 'Chili Powder'],
    dietaryTypes: ['Vegan', 'Vegetarian', 'No Special Preference'],
    allergens: ['Peanuts, Tree Nuts & Soy'],
    suitableFor: [
      'Insufficient_Weight',
      'Normal_Weight',
      'Overweight_Level_I',
      'Overweight_Level_II'
    ],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Boiled Sweet Potato with Lunu Miris',
    mealType: 'Snack',
    description: 'High-fiber boiled sweet potato slices served with spicy onion sambol.',
    portionSize: '1 medium sweet potato',
    calories: 180,
    protein: 2,
    carbohydrates: 40,
    fat: 0,
    fiber: 6,
    ingredients: ['Sweet Potato', 'Onion', 'Chili', 'Lime'],
    dietaryTypes: ['Vegan', 'Vegetarian', 'No Special Preference'],
    allergens: [],
    suitableFor: ['Overweight_Level_I', 'Overweight_Level_II', 'Obesity_Type_I', 'Obesity_Type_II'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Baked Cassava Chips',
    mealType: 'Snack',
    description: 'A healthier baked alternative to deep-fried manioc chips.',
    portionSize: '1 small bowl (50g)',
    calories: 220,
    protein: 1,
    carbohydrates: 45,
    fat: 4,
    fiber: 3,
    ingredients: ['Cassava', 'Olive Oil', 'Salt'],
    dietaryTypes: ['Vegan', 'Vegetarian', 'No Special Preference'],
    allergens: [],
    suitableFor: ['Normal_Weight', 'Overweight_Level_I'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Baked Fish Roll',
    mealType: 'Snack',
    description: 'A classic Sri Lankan short eat filled with spiced fish and potato, baked instead of fried.',
    portionSize: '1 roll',
    calories: 250,
    protein: 8,
    carbohydrates: 30,
    fat: 10,
    fiber: 2,
    ingredients: ['Wheat Flour', 'Fish', 'Potato', 'Onion', 'Spices'],
    dietaryTypes: ['No Special Preference'],
    allergens: ['Gluten', 'Strong Fish Types & Maldive Fish'],
    suitableFor: [
      'Insufficient_Weight',
      'Normal_Weight',
      'Overweight_Level_I'
    ],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Kola Kanda with Jaggery',
    mealType: 'Snack',
    description: 'Nutritious herbal porridge made with rice and leafy greens, paired with a piece of jaggery.',
    portionSize: '1 glass',
    calories: 140,
    protein: 3,
    carbohydrates: 28,
    fat: 2,
    fiber: 3,
    ingredients: ['Gotukola', 'Rice', 'Coconut Milk', 'Jaggery'],
    dietaryTypes: ['Vegan', 'Vegetarian', 'No Special Preference'],
    allergens: [],
    suitableFor: ['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II', 'Obesity_Type_I', 'Obesity_Type_II', 'Obesity_Type_III'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Buffalo Curd with Kithul Treacle',
    mealType: 'Snack',
    description: 'Traditional creamy buffalo milk curd served with pure Sri Lankan kitul palm treacle.',
    portionSize: '1 small cup (100g curd, 1 tbsp treacle)',
    calories: 175,
    protein: 6,
    carbohydrates: 24,
    fat: 6,
    fiber: 0,
    ingredients: ['Buffalo Milk Curd', 'Kithul Treacle'],
    dietaryTypes: ['Vegetarian', 'No Special Preference'],
    allergens: ['Milk & Dairy'],
    suitableFor: ['Insufficient_Weight', 'Normal_Weight', 'Overweight_Level_I'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Boiled Sweet Corn with Chili and Lime',
    mealType: 'Snack',
    description: 'Fresh local sweet corn on the cob rubbed with chili powder, sea salt, and fresh lime.',
    portionSize: '1 medium ear of corn',
    calories: 120,
    protein: 4,
    carbohydrates: 26,
    fat: 2,
    fiber: 3,
    ingredients: ['Sweet Corn', 'Salt', 'Chili Powder', 'Lime'],
    dietaryTypes: ['Vegan', 'Vegetarian', 'No Special Preference'],
    allergens: [],
    suitableFor: ['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II', 'Obesity_Type_I', 'Obesity_Type_II', 'Obesity_Type_III'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Roasted Cashews with Curry Leaves',
    mealType: 'Snack',
    description: 'Raw Ceylon cashew nuts dry-roasted with aromatic curry leaves, black pepper, and sea salt.',
    portionSize: '1 small handful (30g)',
    calories: 180,
    protein: 5,
    carbohydrates: 9,
    fat: 14,
    fiber: 2,
    ingredients: ['Cashew Nuts', 'Curry Leaves', 'Salt', 'Black Pepper'],
    dietaryTypes: ['Vegan', 'Vegetarian', 'No Special Preference'],
    allergens: ['Peanuts, Tree Nuts & Soy'],
    suitableFor: ['Insufficient_Weight', 'Normal_Weight', 'Overweight_Level_I'],
    medicalWarnings: [],
    isActive: true
  },
  {
    name: 'Fresh Pineapple Slices with Chili Salt',
    mealType: 'Snack',
    description: 'Juicy local pineapple chunks seasoned with chili powder and a pinch of salt.',
    portionSize: '1 cup sliced pineapple',
    calories: 85,
    protein: 1,
    carbohydrates: 22,
    fat: 0,
    fiber: 2,
    ingredients: ['Pineapple', 'Salt', 'Black Pepper', 'Chili Powder'],
    dietaryTypes: ['Vegan', 'Vegetarian', 'No Special Preference'],
    allergens: ['Acidic Fruits'],
    suitableFor: ['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II', 'Obesity_Type_I', 'Obesity_Type_II', 'Obesity_Type_III'],
    medicalWarnings: [],
    isActive: true
  }
];

const seedMeals = async () => {
  try {
    await connectDB();
    
    const mealNames = meals.map((meal) => meal.name);

    if (new Set(mealNames).size !== mealNames.length) {
      throw new Error('Duplicate meal names found in seed data');
    }

    await Promise.all(
      meals.map((meal) => new MealTemplate(meal).validate())
    );

    console.log('All 50 seed meals passed schema validation successfully');

    const bulkOps = meals.map(meal => ({
      updateOne: {
        filter: { name: meal.name },
        update: { $set: meal },
        upsert: true
      }
    }));
    
    const result = await MealTemplate.bulkWrite(bulkOps);
    
    const totalCount = await MealTemplate.countDocuments({ isActive: true });
    const breakfastCount = await MealTemplate.countDocuments({ mealType: 'Breakfast', isActive: true });
    const lunchCount = await MealTemplate.countDocuments({ mealType: 'Lunch', isActive: true });
    const dinnerCount = await MealTemplate.countDocuments({ mealType: 'Dinner', isActive: true });
    const snackCount = await MealTemplate.countDocuments({ mealType: 'Snack', isActive: true });
    
    console.log(`Upserted record count: ${result.upsertedCount}`);
    console.log(`Modified record count: ${result.modifiedCount}`);
    console.log(`Total active meal-template count: ${totalCount}`);
    console.log(`Breakfast count: ${breakfastCount}`);
    console.log(`Lunch count: ${lunchCount}`);
    console.log(`Dinner count: ${dinnerCount}`);
    console.log(`Snack count: ${snackCount}`);
    console.log(`\n${SEED_DATA_NOTICE}`);
    
    await mongoose.connection.close();
    process.exit(0);
  } catch (error) {
    console.error(`Error seeding meal templates: ${error.message}`);
    await mongoose.connection.close();
    process.exit(1);
  }
};

seedMeals();
